package tui

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/jasperan/data-in-ai-revolution/internal/workspace"
)

// publishedScreenshotDirs lists every directory the captures are published from.
//
// There are two, and both are genuinely public: the repo-root img/ is embedded by
// README.md and frontend-slides/tui-tour.html, and the package-data copy is shipped
// inside the Python distribution (pyproject.toml lists assets/img/tui-*.svg) and
// embedded by the duplicate deck under src/data_in_ai_revolution/assets/. Nothing
// synchronises them, so a regeneration has to touch both.
func publishedScreenshotDirs(t *testing.T) map[string]string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate this test file to resolve the published image directories")
	}
	root := filepath.Join(filepath.Dir(file), "..", "..")
	return map[string]string{
		"img": filepath.Join(root, "img"),
		"src/data_in_ai_revolution/assets/img": filepath.Join(root,
			"src", "data_in_ai_revolution", "assets", "img"),
	}
}

// The captures embed two kinds of environment noise that must be normalised before
// two runs can be compared at all. Neither is UI:
//
//   - the overview's "Workspace root: <absolute path>" field, which differs per
//     checkout (the two published copies were even generated on different machines,
//     so they disagree today);
//   - the doctor's git check, which renders the live branch name and dirty-file
//     count. The whole detail is normalised, padding and trailing border included:
//     the detail sits inside a fixed-width box, so a count gaining a digit both
//     shifts every trailing pad entity AND can push the closing border off the line.
//     Stopping the match at that border would leave the two sides differing by the
//     one multi-byte character, which is exactly the flake this avoids.
//
// Everything else is compared byte for byte, so real visual drift is still caught.
var workspaceRootField = regexp.MustCompile(`Workspace&#160;root:&#160;[^&<]*`)
var gitStatusField = regexp.MustCompile(`Git&#160;status[^<]*`)

func normaliseEnvironmentNoise(svg []byte) []byte {
	svg = workspaceRootField.ReplaceAll(svg, []byte("Workspace&#160;root:&#160;<workspace>"))
	return gitStatusField.ReplaceAll(svg, []byte("Git&#160;status&#160;<env>"))
}

// TestCaptureSVGsCreatesArtifacts captures the screenshots and, when
// UPDATE_TUI_SCREENSHOTS=1 is set, writes them into every published directory.
//
// This is the regeneration path R3 asks for: previously CaptureSVGs only ever wrote
// to t.TempDir(), so nothing tied the committed img/tui-*.svg to the current UI and
// they silently kept showing the pre-migration terminal.
//
// Regenerate with:
//
//	UPDATE_TUI_SCREENSHOTS=1 go test ./internal/tui/ -run TestCaptureSVGsCreatesArtifacts
func TestCaptureSVGsCreatesArtifacts(t *testing.T) {
	root, err := workspace.Ensure("")
	if err != nil {
		t.Fatalf("ensure workspace: %v", err)
	}

	dirs := publishedScreenshotDirs(t)
	outputDirs := []string{t.TempDir()}
	if os.Getenv("UPDATE_TUI_SCREENSHOTS") == "1" {
		outputDirs = outputDirs[:0]
		for name, dir := range dirs {
			t.Logf("UPDATE_TUI_SCREENSHOTS=1: regenerating published screenshots in %s", name)
			outputDirs = append(outputDirs, dir)
		}
		sort.Strings(outputDirs)
	}

	for _, outputDir := range outputDirs {
		files, err := CaptureSVGs(outputDir, root)
		if err != nil {
			t.Fatalf("capture svgs into %s: %v", outputDir, err)
		}
		if len(files) != 4 {
			t.Fatalf("expected 4 screenshots in %s, got %d", outputDir, len(files))
		}
		for _, file := range files {
			data, readErr := os.ReadFile(filepath.Clean(file))
			if readErr != nil {
				t.Fatalf("read screenshot %s: %v", file, readErr)
			}
			if !strings.HasPrefix(string(data), "<svg") {
				t.Fatalf("expected svg output for %s", file)
			}
		}
	}
}

// driftExempt lists captures that cannot be gated byte-for-byte.
//
// tui-doctor renders the doctor's live git check, so its committed content depends on
// the tree state at capture time: the branch name, the dirty-file count, and -- because
// the checks box is padded to a fixed inner width -- the position of its trailing
// border, which shifts as the count gains a digit. Its rendered length therefore varies
// between runs, and no amount of text normalisation makes the byte stream stable,
// because a longer detail can reflow the box.
//
// It is regenerated by the same command as the rest, so it still gets refreshed; it just
// cannot be asserted. Making it gateable would mean rendering the doctor capture from a
// fixed state rather than the live tree, which changes what the published image shows.
var driftExempt = map[string]string{
	"tui-doctor.svg": "embeds the live git branch and dirty-file count; not byte-stable",
}

// TestCommittedScreenshotsMatchCurrentUI is R3's drift gate. Every published
// tui-*.svg must match the UI the current code renders, in BOTH published
// directories.
//
// The originals had fallen a long way behind: the package-data copy still used an
// older palette (#07111f rather than #1e1e2e), so it predated far more than the
// Bubbles v2 migration.
//
// The comparison normalises the environment-dependent fields described above so the
// gate is stable across checkouts and unrelated edits; every other byte must match.
func TestCommittedScreenshotsMatchCurrentUI(t *testing.T) {
	root, err := workspace.Ensure("")
	if err != nil {
		t.Fatalf("ensure workspace: %v", err)
	}

	generated := t.TempDir()
	files, err := CaptureSVGs(generated, root)
	if err != nil {
		t.Fatalf("capture svgs: %v", err)
	}
	if len(files) != 4 {
		t.Fatalf("expected 4 generated screenshots, got %d", len(files))
	}

	dirs := publishedScreenshotDirs(t)
	names := make([]string, 0, len(dirs))
	for name := range dirs {
		names = append(names, name)
	}
	sort.Strings(names)

	compared := 0
	for _, dirName := range names {
		dir := dirs[dirName]
		for _, file := range files {
			name := filepath.Base(file)
			if reason, exempt := driftExempt[name]; exempt {
				t.Logf("skipping %s/%s: %s", dirName, name, reason)
				continue
			}
			fresh, err := os.ReadFile(filepath.Clean(file))
			if err != nil {
				t.Fatalf("read generated %s: %v", name, err)
			}
			committed, err := os.ReadFile(filepath.Join(dir, name))
			if err != nil {
				t.Errorf("published screenshot %s/%s is missing: %v", dirName, name, err)
				continue
			}
			compared++
			if !bytes.Equal(normaliseEnvironmentNoise(fresh), normaliseEnvironmentNoise(committed)) {
				t.Errorf("%s/%s is stale: it does not match the current UI "+
					"(%d committed bytes vs %d generated).\n"+
					"Regenerate with: UPDATE_TUI_SCREENSHOTS=1 go test ./internal/tui/ -run TestCaptureSVGsCreatesArtifacts",
					dirName, name, len(committed), len(fresh))
			}
		}
	}
	if compared == 0 {
		t.Fatal("drift gate compared nothing; the sweep is vacuous")
	}
}
